<?php

namespace ContainerRqJLj02;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Core\Controller\DefaultController' shared autowired service.
     *
     * @return \App\Core\Controller\DefaultController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Core\\Controller\\DefaultController'] = new \App\Core\Controller\DefaultController();
    }
}
