<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRcznAxg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRcznAxg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRcznAxg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRcznAxg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRcznAxg\App_KernelDevDebugContainer([
    'container.build_hash' => 'RcznAxg',
    'container.build_id' => '39f3fc3c',
    'container.build_time' => 1637016572,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRcznAxg');
