<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_api_test_index' => [[], ['_controller' => 'App\\Api\\Controller\\TestController::index'], [], [['text', '/api/test/']], [], []],
    'app_api_test_users' => [[], ['_controller' => 'App\\Api\\Controller\\TestController::users'], [], [['text', '/api/test/users']], [], []],
    'app_core_default_index' => [[], ['_controller' => 'App\\Core\\Controller\\DefaultController::indexAction'], [], [['text', '/']], [], []],
];
